import type { Metadata } from "next";
import { Geist, Geist_Mono, Inclusive_Sans, Fauna_One } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inclusiveSans = Inclusive_Sans({
  weight: ['400', '400', '700', '700'], // Specify desired weights/styles
  subsets: ['latin'], // Specify required subsets
  display: 'swap', // 'swap' ensures text is visible while the font loads
  variable: '--font-inclusive-sans', // Optional: use a CSS variable
});

const faunaOne = Fauna_One({
  weight: '400', // Specify desired weights/styles
  subsets: ['latin'], // Specify required subsets
  display: 'swap', // 'swap' ensures text is visible while the font loads
  variable: '--font-fauna-one', // Use a unique CSS variable
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${inclusiveSans.variable} ${faunaOne.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
